### ISSUE TITLE
result image shown twice

### ISSUE THREAD

**Issue by tischi** [fiji/Correct_3D_Drift#2]
The result images was shown twice in a sense that the imp.show() command was occurring two times in the code. In GUI usage this did not matter, but it appears that when running the script from within and IJ macro with `setBatchMode( true )` there are two result images, which apparently leads to erroneous behaviors (reported by user on IJ Forum). 
I removed the second imp.show().

@ctrueden: Could you release the new version?

**Comment by imagejan** [comment]
@tischi you should be able to release it yourself using [`release-version.sh`](https://github.com/scijava/scijava-scripts/blob/master/release-version.sh) (see also [the wiki page](https://imagej.net/Development_Lifecycle#Phase_3:_Released)).

Once it is released, it can be uploaded to update site.

**Comment by tischi** [comment]
I will try later today!

**Comment by tischi** [comment]
OK. I did it! Do you know when it will be available to the users?

**Comment by imagejan** [comment]
Great. That means the jar file is now available on the maven repository:
http://maven.imagej.net/#nexus-search;quick~Correct_3D_Drift

> Do you know when it will be available to the users?

As I wrote before:

> Once it is released, it can be uploaded to update site.

Currently, this has to be done manually. I don't know if you have access to the update site; if you have, you can upload via the ImageJ updater. If not, it's up to @ctrueden or another maintainer.

**Comment by ctrueden** [comment]
I updated the version in the pom-scijava Bill of Materials: scijava/pom-scijava@67882741e6a5f2d9cf051e5c4328e230fb3a60cb.

That trickles downstream to https://github.com/fiji/fiji in the form of an updated parent POM.

I don't have a time estimate on when I will upload the next batch of components. Still trying to dig my way out of backlog after the last two hackathons, while making progress on SciJava Common.

**Comment by ctrueden** [comment]
For this new release, I'm just going to upload it manually now.

**Comment by ctrueden** [comment]
I uploaded it.

@tinevez @bhoeckendorf @bogovicj Note that I initially ran into problems with the dreaded "Failed to retrieve OPTIONS for WebDAV actions" error that has been plaguing Janelia Research Campus. The culprit was that I was using `https://sites.imagej.net/Java-8` instead of plain `http://sites.imagej.net/Java-8` for my site URL. Is it possible you had configured the same?
