### ISSUE TITLE
Feature Request: Restrict shifts to x and y dimension

### ISSUE THREAD

**Issue by JuliaS92** [fiji/Correct_3D_Drift#3]
Hi there,
I really like this tool and I use it in one of my projects.
I deal with movies, that are acquired in fixed z-stacks, which don't drift. However, the plugin sometimes detects a z-shift and corrects it, which then messes up the rest of the down-stream processing, where I combine several movies.
It would be great if there was an option to restrict the shifts to x and y dimensions instead of fixing the file output of the virtual processing afterwards.
Whether you implement it or not, thanks anyway :)
Julia

**Comment by tischi** [comment]
Very good idea. I'll work on it....

**Comment by tischi** [comment]
There could be two ways:

1) Make on-the-fly average projections along z; register the projected images in x-y; apply the x-y shift to the 3D input data. (This would be faster, because the registration is only in 2d; however if you loose the contrast that you want to register during the average projection you might not find the correct drift anymore)

2) Compute x-y-z shifts; set the z component of the shift to zero; and apply. (This is slower and the algorithm might even find wrong x/y shifts because it tried to jump somewhere weird in z, but you can find image features really in 3d).

What do you think?

Are the x-y shifts that it currently finds for your data correct? 
Or are they wrong because it finds a completely wrong x&y&z shift?

**Comment by JuliaS92** [comment]
Hi there,
thanks for considering the change!

The x-y shifts it's currently finding for our data is correct, and we anyway track objects afterwards, which has some tolerance for errors. Still my suggestion would be a variant of the first option:

Maybe you can include an option to select which slices to use for the z-projection. e.g. register the whole stack of 10 slices but only use slices 4-7 for the z-projection, similar to selecting the channel to be used. This way you can select the slices with the highest contrast and still do it on more than just one.

**Comment by tischi** [comment]
Hi Julia,

Selecting a range of z-planes is already implemented:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/2157566/48979629-3ea12200-f0be-11e8-855b-368d9020bff7.png">

I would then suggest adding a checkbox: "Correct drift only in x/y"
And it would then compute  an avg-projection using the zMin, zMax range that you entered.
Ok?

Just to make sure: does the user interface (UI) look like below for you?

<img width="541" alt="image" src="https://user-images.githubusercontent.com/2157566/48979768-ac9a1900-f0bf-11e8-9976-34b3f9c2b59e.png">

**Comment by JuliaS92** [comment]
Hi Christian,

yes, this is what it looks like. I thought, that the z-plane selection was for which planes to register at all, sorry for that. So yes, what sou suggest is exactly what I was looking for.

Thanks!

**Comment by tischi** [comment]
" I thought, that the z-plane selection was for which planes to register at all, " 

Good point...let me check that :-)

**Comment by tischi** [comment]
I implemented your wish. Could you please test attached file?
If it works for you I will upload to Fiji.
[Correct_3D_drift.py.zip](https://github.com/fiji/Correct_3D_Drift/files/2626080/Correct_3D_drift.py.zip)

**Comment by JuliaS92** [comment]
Great thanks 👍
I will test it asap and let you know whether it works and if it makes a difference for the x-y shifts.

**Comment by JuliaS92** [comment]
Hi there,
sorry it took a while.
So the suppression of the z drift correction definitely works. Files that generated an extra z-plane wihtout the tick don't anymore.
However the x-y drift is slightly different even for those that should be the same before and after just judging by the target image dimensions:
```
                  with z      without z
shifting before   2063x2064   2066x2074
non-shifting      2236x2080   2248x2081
```
The original size is 2048x2044.
For our purposes this is fine though, as we anyway track objects afterwards.

If you want me to try it out again at some point just let me know :D

**Comment by tischi** [comment]
A similar request was raised on the forum: https://forum.image.sc/t/imagej-correct-3d-drift-memory-leak/33676/11
