### ISSUE TITLE
Using Correct_3d_drift on .tif files

### ISSUE THREAD

**Issue by akatav** [fiji/Correct_3D_Drift#6]
I have .tif files captured on a field of view of mouse brain using 2d photon microscopy. There is no time axis for now. Each frame in the .tif file represents the tissue at a depth 'z'. These frames are not aligned properly. Can i use your tool to align such frames?

**Comment by tischi** [comment]
Thank you for the question.
May I please ask you to ask this question on www.image.sc?
Please, in your post write @Christian_Tischer, this will notify me.
Already to answer, I think tools like https://imagej.net/StackReg might be better suited for your data.

**Comment by akatav** [comment]
@tischi i have already raised a question on image.sc - https://forum.image.sc/t/align-frames-in-tiff-file-derived-from-2d-photon-microscopy-of-rat-brain/33930
My images are from a live animal with motion artifacts. I am not sure if StackReg or TurboReg can register images from different FOVs along the axial plane, in this case.
